name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: |
        pnpm install
        cd api && npm install
    
    - name: Build frontend
      run: pnpm build
    
    - name: Build backend
      run: cd api && npm run build
    
    - name: Run frontend linting
      run: pnpm lint
    
    - name: Run backend linting
      run: cd api && npm run lint 